# Generated by Django 2.2 on 2019-06-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.UUIDField(default=232643706114782439146272182542059985465, editable=False, unique=True),
        ),
    ]
