# Generated by Django 2.2 on 2019-06-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20190607_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
