# Generated by Django 2.2 on 2019-06-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20190607_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.BigIntegerField(editable=False, unique=True),
        ),
    ]
