# Generated by Django 2.2 on 2019-06-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_installment_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
