# Generated by Django 2.2 on 2019-06-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_late_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='interest',
            new_name='late_fee',
        ),
    ]
