# Generated by Django 2.2 on 2019-06-06 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canceled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=200)),
                ('name', models.CharField(max_length=150)),
                ('taxid', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('cellphone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
