# Generated by Django 2.2.1 on 2019-05-24 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
                ('data_cancelamento', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Cancelamento')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('uuid', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=200)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
